#!/bin/bash
#SBATCH --job-name=rebound
#SBATCH --nodes=1
#SBATCH --partition=workq
#SBATCH --time=01:00:00
#SBATCH --account=pawsey0152
#SBATCH --export=NONE

### stdout and stderr
#SBATCH --output=myjob-%j.log
#SBATCH --error=myjob-%j.err

#SBATCH --mail-type=ALL
#SBATCH --mail-user=hadriendvpx@gmail.com


export OMP_NUM_THREADS=24
export LD_LIBRARY_PATH=/group/pawsey0213/software/cle52up04/apps/PrgEnv-gnu/5.2.82/gcc/4.8.2/haswell/libmatheval/1.1.11/lib:$LD_LIBRARY_PATH

# aprun -n 1 -d ./rebound.x archive.bin 10000.0
